version: '3.7'

networks:
  default:
      name: default-network

services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    restart: on-failure:5
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${ROOT_PASSWORD}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ./data:/data/db
    networks:
      - default

