version: '3.5'

networks:
  default:
    name: default-network

services:
  mariadb:
    image: mariadb:11.1.2
    # restart: unless-stopped
    restart: on-failure:5
    container_name: mariadb
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql
      - ./config/specific.cnf:/etc/mysql/conf.d/specific.cnf:ro
    networks:
      - default
    environment:
      - MARIADB_ROOT_HOST=%
      - MARIADB_ROOT_PASSWORD=YgNViJ7jjNc01qJZ1@
