version: '3.6'

networks:
  default:
    name: default-network

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - '8000:9000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    restart: always
    networks:
      - default
