version: "3.5"

networks:
  default:
    name: default-network

services:
  traefik:
    image: traefik:v2.4
    container_name: traefik
    networks:
      - default
    ports:
      - "443:443"
      - "80:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - './traefik.toml:/traefik.toml'
      - './acme.json:/acme.json'
      - './traefik_dynamic.toml:/traefik_dynamic.toml'
    # labels:
    #   - traefik.enable=true
    #   - traefik.network=https
    #   - traefik.port=8080
    #   - traefik.http.routers.traefik.service=api@internal
    #   - traefik.http.routers.traefik.rule=Host(`proxy.your_domain.com`)
    #   - traefik.http.routers.traefik.middlewares=traefik-auth
