[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:$apr1$tv3carHm$KPB8yg9Ph4V6awdBLUz/o1"
  ]

[http.routers.api]
  rule = "Host(`proxy.your_domain.com`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"

